services:
  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - $HOME/.apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  backend:
    name: backend
