spring:
  application:
    name: peridot
  profiles:
    active: ${PERIDOT_ENV}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  error:
    include-message: always
jwt:
  secret: ${JWT_SECRET}
  token-expiration: ${JWT_TOKEN_EXPIRATION:86400000} # 1 day in milliseconds