databaseChangeLog:
  - changeSet:
      id: 1.0.6
      author: jonichi
      changes:
        - createSequence:
            sequenceName: envelope_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: envelope
            columns:
              - column:
                  name: id
                  type: INTEGER
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: INTEGER
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: status
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP WITH TIME ZONE
  - changeSet:
      id: 1.0.6-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.6

  - changeSet:
      id: 1.0.7
      author: jonichi
      changes:
        - addUniqueConstraint:
            tableName: envelope
            columnNames: user_id, name
            constraintName: user_id_name_unique
        - addForeignKeyConstraint:
            constraintName: fk_user_envelope
            baseTableName: envelope
            baseColumnNames: user_id
            referencedTableName: _user
            referencedColumnNames: id
        - addForeignKeyConstraint:
            constraintName: fk_reference_code_envelope_status
            baseTableName: envelope
            baseColumnNames: status
            referencedTableName: reference_code
            referencedColumnNames: code
  - changeSet:
      id: 1.0.7-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.7

  - changeSet:
      id: 1.0.8
      author: jonichi
      changes:
        - createSequence:
            sequenceName: budget_envelope_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: budget_envelope
            columns:
              - column:
                  name: id
                  type: INTEGER
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: budget_id
                  type: INTEGER
                  constraints:
                    nullable: false
              - column:
                  name: envelope_id
                  type: INTEGER
                  constraints:
                    nullable: false
              - column:
                  name: amount
                  type: DECIMAL(10, 2)
                  constraints:
                    nullable: false
              - column:
                  name: recurring
                  type: BOOLEAN
                  defaultValue: false
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP WITH TIME ZONE
  - changeSet:
      id: 1.0.8-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.8

  - changeSet:
      id: 1.0.9
      author: jonichi
      changes:
        - addForeignKeyConstraint:
            constraintName: fk_budget_budget_envelope
            baseTableName: budget_envelope
            baseColumnNames: budget_id
            referencedTableName: budget
            referencedColumnNames: id
        - addForeignKeyConstraint:
            constraintName: fk_envelope_budget_envelope
            baseTableName: budget_envelope
            baseColumnNames: envelope_id
            referencedTableName: envelope
            referencedColumnNames: id
        - addForeignKeyConstraint:
            constraintName: fk_reference_code_budget_envelope_status
            baseTableName: budget_envelope
            baseColumnNames: status
            referencedTableName: reference_code
            referencedColumnNames: code
  - changeSet:
      id: 1.0.9-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.9

  - changeSet:
      id: test-data-1.0.1
      author: jonichi
      context: dev, test
      changes:
        - insert:
            tableName: budget
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: user_id
                  value: 1
              - column:
                  name: amount
                  value: 22500.00
              - column:
                  name: period
                  value: 2024-12-1
              - column:
                  name: status
                  value: BUDGET_STATUS_INCOMPLETE
              - column:
                  name: created_date
                  valueComputed: CURRENT_TIMESTAMP
        - sql:
            comment: "Resynchronize budget_sequence"
            sql: "SELECT setval('budget_sequence', (SELECT MAX(id) FROM budget));"

  - changeSet:
      id: test-data-1.0.2
      author: jonichi
      context: dev, test
      changes:
        - insert:
            tableName: envelope
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: user_id
                  value: 1
              - column:
                  name: name
                  value: Test Envelope 1
              - column:
                  name: status
                  value: SYSTEM_STATUS_ACTIVE
              - column:
                  name: created_date
                  valueComputed: CURRENT_TIMESTAMP
        - sql:
            comment: "Resynchronize envelope_sequence"
            sql: "SELECT setval('envelope_sequence', (SELECT MAX(id) FROM envelope));"

  - changeSet:
      id: test-data-1.0.3
      author: jonichi
      context: dev, test
      changes:
        - insert:
            tableName: envelope
            columns:
              - column:
                  name: id
                  value: 2
              - column:
                  name: user_id
                  value: 1
              - column:
                  name: name
                  value: Test Envelope 2
              - column:
                  name: status
                  value: SYSTEM_STATUS_ACTIVE
              - column:
                  name: created_date
                  valueComputed: CURRENT_TIMESTAMP
        - sql:
            comment: "Resynchronize envelope_sequence"
            sql: "SELECT setval('envelope_sequence', (SELECT MAX(id) FROM envelope));"
