databaseChangeLog:
  - changeSet:
      id: 1.0.0
      author: jonichi
      changes:
        - createTable:
            tableName: reference_code
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: code
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: reference_code_unique
              - column:
                  name: category
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: TEXT
  - changeSet:
      id: 1.0.0-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.0

  - changeSet:
      id: 1.0.1
      author: jonichi
      changes:
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: USER_ROLE_ACCOUNT
              - column:
                  name: description
                  value: Standard user role
              - column:
                  name: category
                  value: USER_ROLE
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: SYSTEM_STATUS_ACTIVE
              - column:
                  name: description
                  value: Active
              - column:
                  name: category
                  value: SYSTEM_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: SYSTEM_STATUS_INACTIVE
              - column:
                  name: description
                  value: Inactive
              - column:
                  name: category
                  value: SYSTEM_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: BUDGET_STATUS_COMPLETE
              - column:
                  name: description
                  value: Status when allocation is complete
              - column:
                  name: category
                  value: BUDGET_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: BUDGET_STATUS_INCOMPLETE
              - column:
                  name: description
                  value: Status when allocation is incomplete
              - column:
                  name: category
                  value: BUDGET_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: BUDGET_STATUS_INVALID
              - column:
                  name: description
                  value: Status when allocation is invalid
              - column:
                  name: category
                  value: BUDGET_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: ENVELOPE_STATUS_UNDER
              - column:
                  name: description
                  value: Status when envelope amount is more than expenses
              - column:
                  name: category
                  value: ENVELOPE_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: ENVELOPE_STATUS_FULL
              - column:
                  name: description
                  value: Status when envelope amount is equal to expenses
              - column:
                  name: category
                  value: ENVELOPE_STATUS
        - insert:
            tableName: reference_code
            columns:
              - column:
                  name: code
                  value: ENVELOPE_STATUS_EXCEEDED
              - column:
                  name: description
                  value: Status when envelope amount is less than expenses
              - column:
                  name: category
                  value: ENVELOPE_STATUS
  - changeSet:
      id: 1.0.1-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.1

  - changeSet:
      id: 1.0.2
      author: jonichi
      changes:
        - createSequence:
            sequenceName: _user_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: _user
            columns:
              - column:
                  name: id
                  type: INTEGER
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: user_username_unique
              - column:
                  name: email
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: user_email_unique
              - column:
                  name: password
                  type: VARCHAR(75)
                  constraints:
                    nullable: false
              - column:
                  name: role
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP WITH TIME ZONE
  - changeSet:
      id: 1.0.2-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.2

  - changeSet:
      id: 1.0.3
      author: jonichi
      changes:
        - addForeignKeyConstraint:
            constraintName: fk_reference_code_user_role
            baseTableName: _user
            baseColumnNames: role
            referencedTableName: reference_code
            referencedColumnNames: code
  - changeSet:
      id: 1.0.3-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.3

  - changeSet:
      id: test-data-1.0.0
      author: jonichi
      context: dev, test
      changes:
        - insert:
            tableName: _user
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: username
                  value: jon
              - column:
                  name: email
                  value: jon@mail.com
              - column:
                  name: password
                  value: $2a$12$q8TAcKs7mjnXPI7/MOWnU.cTpYpwJZe/OuBbrAVw13.aA6MjO6l32
              - column:
                  name: role
                  value: USER_ROLE_ACCOUNT
              - column:
                  name: created_date
                  valueComputed: CURRENT_TIMESTAMP
        - sql:
            comment: "Resynchronize _user_sequence"
            sql: "SELECT setval('_user_sequence', (SELECT MAX(id) FROM _user));"

  - changeSet:
      id: test-data-1.0.1
      author: jonichi
      context: dev, test
      changes:
        - insert:
            tableName: _user
            columns:
              - column:
                  name: id
                  value: 2
              - column:
                  name: username
                  value: testuser
              - column:
                  name: email
                  value: testuser@mail.com
              - column:
                  name: password
                  value: $2a$12$q8TAcKs7mjnXPI7/MOWnU.cTpYpwJZe/OuBbrAVw13.aA6MjO6l32
              - column:
                  name: role
                  value: USER_ROLE_ACCOUNT
              - column:
                  name: created_date
                  valueComputed: CURRENT_TIMESTAMP
        - sql:
            comment: "Resynchronize _user_sequence"
            sql: "SELECT setval('_user_sequence', (SELECT MAX(id) FROM _user));"

  - changeSet:
      id: 1.0.4
      author: jonichi
      changes:
        - createSequence:
            sequenceName: budget_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: budget
            columns:
              - column:
                  name: id
                  type: INTEGER
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: INTEGER
                  constraints:
                    nullable: false
              - column:
                  name: amount
                  type: DECIMAL(10, 2)
                  constraints:
                    nullable: false
              - column:
                  name: period
                  type: DATE
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP WITH TIME ZONE
  - changeSet:
      id: 1.0.4-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.4

  - changeSet:
      id: 1.0.5
      author: jonichi
      changes:
        - addForeignKeyConstraint:
            constraintName: fk_user_budget
            baseTableName: budget
            baseColumnNames: user_id
            referencedTableName: _user
            referencedColumnNames: id
        - addForeignKeyConstraint:
            constraintName: fk_reference_code_budget_status
            baseTableName: budget
            baseColumnNames: status
            referencedTableName: reference_code
            referencedColumnNames: code
        - addUniqueConstraint:
            tableName: budget
            columnNames: user_id, period
            constraintName: user_id_period_unique
  - changeSet:
      id: 1.0.5-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.5
