databaseChangeLog:
  - changeSet:
      id: 1.0.0
      author: jonichi
      changes:
        - createSequence:
            sequenceName: _user_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: _user
            columns:
              - column:
                  name: id
                  type: INTEGER
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: user_username_unique
              - column:
                  name: email
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: user_email_unique
              - column:
                  name: password
                  type: VARCHAR(75)
                  constraints:
                    nullable: false
              - column:
                  name: role
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
  - changeSet:
      id: 1.0.0-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.0

  - changeSet:
      id: test-data-1.0.0
      author: jonichi
      context: dev
      changes:
        - insert:
            tableName: _user
            columns:
              - column:
                  name: username
                  value: jon
              - column:
                  name: email
                  value: jon@mail.com
              - column:
                  name: password
                  value: $2a$12$q8TAcKs7mjnXPI7/MOWnU.cTpYpwJZe/OuBbrAVw13.aA6MjO6l32
              - column:
                  name: role
                  value: USER
        - sql:
            comment: "Resynchronize _user_sequence"
            sql: "SELECT setval('_user_sequence', (SELECT MAX(id) FROM _user));"

  - changeSet:
      id: 1.0.1
      author: jonichi
      changes:
        - createSequence:
            sequenceName: budget_sequence
            startValue: 1
            incrementBy: 1
        - createTable:
            tableName: budget
            columns:
              - column:
                  name: id
                  type: INTEGER
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: INTEGER
                  constraints:
                    nullable: false
              - column:
                  name: amount
                  type: DECIMAL(10, 2)
                  constraints:
                    nullable: false
              - column:
                  name: period
                  type: DATE
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false

  - changeSet:
      id: 1.0.1-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.1

  - changeSet:
      id: 1.0.2
      author: jonichi
      changes:
        - addForeignKeyConstraint:
            constraintName: fk_user_budget
            baseTableName: budget
            baseColumnNames: user_id
            referencedTableName: _user
            referencedColumnNames: id

  - changeSet:
      id: 1.0.2-tag
      author: jonichi
      changes:
        - tagDatabase:
            tag: 1.0.2
