name: peridot-backend

on: [pull_request]

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Send discord in_progress notification
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "Bob",
            "embeds": [
              {
                "type": "rich",
                "title": "Code checking PR #${{ github.event.number }} on ${{ github.event.repository.name }}",
                "description": "#${{ github.event.number }}: ${{ github.event.pull_request.title }}\n\n${{ github.event.repository.name }}: ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}",
                "color": 13408512,
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "url": "${{ github.event.pull_request.html_url }}",
                "fields": [
                  {
                    "name": "Description",
                    "value": "${{ github.event.pull_request.body || '\n' }}",
                    "inline": "false"
                  },
                  {
                    "name": "Status",
                    "value": "IN_PROGRESS",
                    "inline": "true"
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.actor }}",
                    "inline": "true"
                  },
                  {
                    "name": "Files Affected",
                    "value": "${{ github.event.pull_request.changed_files }} files",
                    "inline": "false"
                  }
                ]
              }
            ]
          }' ${{ secrets.WEBHOOK_URL }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -ntp --file pom.xml -DskipTests

      - name: Run Tests
        run: mvn test -ntp

      - name: Run linting
        run: |
          chmod +x ./run
          ./run lint

      # TODO: add dependabot

  result:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3

      - name: Send discord success notification
        if: ${{ needs.build.result == 'success' }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "Bob",
            "embeds": [
              {
                "type": "rich",
                "title": "PR #${{ github.event.number }} on ${{ github.event.repository.name }} passed code check!",
                "description": "#${{ github.event.number }}: ${{ github.event.pull_request.title }}\n\n${{ github.event.repository.name }}: ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}",
                "color": 3381555,
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "url": "${{ github.event.pull_request.html_url }}",
                "fields": [
                  {
                    "name": "Description",
                    "value": "${{ github.event.pull_request.body || '\n' }}",
                    "inline": "false"
                  },
                  {
                    "name": "Status",
                    "value": "SUCCESS",
                    "inline": "true"
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.actor }}",
                    "inline": "true"
                  },
                  {
                    "name": "Files Affected",
                    "value": "${{ github.event.pull_request.changed_files }} files",
                    "inline": "false"
                  }
                ]
              }
            ]
          }' ${{ secrets.WEBHOOK_URL }}
          echo "${{ toJson(needs) }}"

      - name: Send discord failed notification
        if: ${{ needs.build.result == 'failure' }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "Bob",
            "embeds": [
              {
                "type": "rich",
                "title": "PR #${{ github.event.number }} on ${{ github.event.repository.name }} hit a snag!",
                "description": "#${{ github.event.number }}: ${{ github.event.pull_request.title }}\n\n${{ github.event.repository.name }}: ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}",
                "color": 13369344,
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "url": "${{ github.event.pull_request.html_url }}",
                "fields": [
                  {
                    "name": "Description",
                    "value": "${{ github.event.pull_request.body || '\n' }}",
                    "inline": "false"
                  },
                  {
                    "name": "Status",
                    "value": "FAILURE",
                    "inline": "true"
                  },
                  {
                    "name": "Author",
                    "value": "${{ github.actor }}",
                    "inline": "true"
                  },
                  {
                    "name": "Files Affected",
                    "value": "${{ github.event.pull_request.changed_files }} files",
                    "inline": "false"
                  }
                ]
              }
            ]
          }' ${{ secrets.WEBHOOK_URL }}
          echo "${{ toJson(needs) }}"